### ISSUE TITLE
REGISTERS.md seems outdated compared to REFERENCE.md

### ISSUE THREAD

**Issue by roscopeco** [XarkLabs/Xosera#57]
The `REGISTERS.md` file lists audio registers as TODO, and has blitter registers occupying the space that, according to `REFERENCE.md` is allocated for the audio registers.

Unless I'm reading it wrong (which is totally possible), this might become confusing 🙂

**Comment by XarkLabs** [comment]
Thanks, 100% correct.  The reference has grown to be too much in some ways, but I have not kept the register guide up to date.  Even when up to date, this is still not a "great" quick reference...

**Comment by XarkLabs** [comment]
I updated REGISTERS and tweaked the format a bit.  Seems generally better than nothing for quick-ish reference. newlib-develop #24f1342
