### ISSUE TITLE
`PIXEL_Y` register has inconsistent name in `REFERENCE.md`

### ISSUE THREAD

**Issue by roscopeco** [XarkLabs/Xosera#58]
In `REFERENCE.md` the pixel X register is named `XM_PIXEL_X` but the corresponding Y register is named `PIXEL_Y` - is this intentional?

**Comment by XarkLabs** [comment]
No.  Fixed to be consistent.

**Comment by XarkLabs** [comment]
Fix submitted in newlib-develop #24f1342 thanks so much for mentioning this.
